config/routes.rb
Tavo::Application.routes.draw do  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "signup" => "users#new", :as => "signup"
  resources :users
  resources :sessions
  resources :password_resets
  get "dashboard" => "dashboard#index"
  
  resources :projects
  resources :references
  resources :documents
  resources :images
  resources :imagetags
  resources :sites
  resources :appellations
  resources :districts
  resources :people
  post "user_connect" => "people#connect_to_user"
  resources :surveys do
    resources :visits
  end

  root :to => 'discover#index'

end

app/models/visit.rb
class Visit < ActiveRecord::Base
  stampable
  attr_accessible :start_date, :end_date, :documents_attributes, :creator_id, :updater_id
  belongs_to :survey
  has_many :imagetags, :as => :imageable, :dependent => :destroy
  has_many :images, :through => :imagetags
  has_many :documents, :as => :documentable, :dependent => :destroy

  accepts_nested_attributes_for :documents, :reject_if => lambda { |a| a[:content].blank? }, :allow_destroy => true

  validates_presence_of :start_date, :end_date
end

app/controllers/visits_controller.rb
class VisitsController < ApplicationController
  def index
    @survey = Survey.find(params[:survey_id])
    @visits = @survey.visits.all
    #render :layout => "index_template"
  end

  def show
    @visit = Visit.find(params[:id])
    render :layout => "show_template"
  end

  def new
    @survey = Survey.find(params[:survey_id])
    @visit = @survey.visits.build
  end

  def create
    @survey = Survey.find(params[:survey_id])
    @visit = @survey.visits.build(params[:visit])
    if @visit.save
      redirect_to survey_visit_url(@visit.survey, @visit), :notice => "Successfully created visit."
    else
      render :action => 'new'
    end
  end

  def edit
    @survey = Survey.find(params[:survey_id])
    @visit = @survey.visits.find(params[:id])
  end

  def update
    @visit = Visit.find(params[:id])
    if @visit.update_attributes(params[:visit])
      redirect_to survey_visit_url(@visit.survey, @visit), :notice  => "Successfully updated visit."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @visit = Visit.find(params[:id])
    @visit.destroy
    redirect_to survey_visits_url(@visit.survey), :notice => "Successfully destroyed visit."
  end
end

app/helpers/visits_helper.rb
module VisitsHelper
end

app/views/visits/_document_fields.html.erb
<div class="field">
  <div class="control-group">
    <%= f.label :documenttype, :class => 'control-label' %>
    <div class="controls">
      <%= f.select(:documenttype, Document::DOCUMENTTYPES, :class => 'select-field') %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :title, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :title, :class => 'text-field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :content, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :content, :class => 'text-area' %>
    </div>
  </div>
  <small><%= f.link_to_remove "Diese Beschreibung entfernen" %></small>
</div>

app/views/visits/_form.html.erb
<%= f.error_messages %>

<div class="control-group">
  <%= f.label :start_date, :class => 'control-label' %>
  <div class="controls">
    <%= f.datetime_select :start_date, :class => 'text-field' %>
  </div>
</div>
<div class="control-group">
  <%= f.label :end_date, :class => 'control-label' %>
  <div class="controls">
    <%= f.datetime_select :end_date, :class => 'text-field' %>
  </div>
</div>

<%= f.fields_for :documents do |builder| %>
  <%= render "document_fields", :f => builder %>
<% end %>
<p><%= f.link_to_add "Einen Bericht hinzufügen", :documents %></p>

<div class="form-actions">
  <%= f.submit "Speichern", :class => 'btn btn-primary' %>
  <% if @visit.new_record? %>
    <%= link_to 'Abbrechen', survey_path(@visit.survey), :class => 'btn' %>
  <% else %>
    <%= link_to 'Abbrechen', survey_visit_path(@visit.survey, @visit), :class => 'btn' %>
  <% end %>
</div>

app/views/visits/_report_fields.html.erb
<div class="field">
  <div class="control-group">
    <%= f.label :reporttype, :class => 'control-label' %>
    <div class="controls">
      <%= f.select(:reporttype, Report::REPORTTYPES, :class => 'select-field') %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :title, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :title, :class => 'text-field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :reporttext, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :reporttext, :class => 'text-area' %>
    </div>
  </div>
  <small><%= f.link_to_remove "Diese Beschreibung entfernen" %></small>
</div>

app/views/visits/edit.html.erb
<% title "Besuch bearbeiten" %>

  <%= nested_form_for([@survey, @visit], :url => survey_visit_path) do |f| %>
    <%= render 'form', :f => f %>

  <% end %>

app/views/visits/index.html.erb
<% title "nicht vorgesehen" %>
<!--
<% content_for :overview do %>
  <p>
    als Teil der Begehung am Siedlungsplatz von <strong><%= link_to "#{@survey.site.name} (#{@survey.number})", @survey %></strong> für das Projekt <%= link_to "#{@survey.project.name}", project_path(@survey.project) %>. <small>(<%= link_to "zur Siedlungsplatzansicht", @survey.site %>)</small>
  </p>
<% end %>

<% content_for :thead do %>
<% unless @survey.visits.empty? %>
  <tr>
    <th class="span2">Datum</th>
    <th class="span3">Dauer</th>
    <% if logged_in? %>
      <th></th>
    <% end %>
  </tr>
<% else %>
  <tr>
    <th class="span6"></th>
    <th class="span2"></th>
  </tr>
<% end %>
<% end %>

<% content_for :tbody do %>
  <% unless @survey.visits.empty? %>
    <% for visit in @visits %>
      <tr>
        <td><%= link_to "#{visit.start_date.strftime("%d.%m.%Y")}", survey_visit_path(visit.survey, visit) %></td>
        <td><%= convert_seconds_to_time(visit.start_date, visit.end_date) %></td>
        <% if logged_in? %>
          <td style="text-align:right;">
            <%= link_to "Bearbeiten", edit_survey_visit_path(visit.survey, visit), :class => 'btn btn-mini' %>
          </td>
        <% end %>
      </tr>
    <% end %>
  <% else %>
    <tr>
      <td>Der Ort wurde bisher noch nicht durch das Projekt besucht.</td>
      <% if logged_in? %>
        <td><%= link_to "Informationen zu einem neuen Besuch aufnehmen", new_survey_visit_path(@survey) %>.</td>
      <% end %>
    </tr>
  <% end %>
<% end %>

<% content_for :indexsidebar do %>
  <p></p>
<% end %>

-->

app/views/visits/new.html.erb
<% title "Neuer Besuch in #{@survey.site.name} durch #{@survey.project.name}" %>

<%= nested_form_for([@survey, @visit], :url => survey_visits_path) do |f| %>
  <%= render 'form', :f => f %>


<% end %>

app/views/visits/show.html.erb
<% title "Besuch von #{@visit.survey.site.name} am #{@visit.start_date.strftime("%d.%m.%Y")}" %>
<% content_for :overview do %>
  <p>
    Übersicht aller Besuche durch <%= @visit.survey.project.name %> an diesem Siedlungsplatz <%= link_to "ansehen", survey_path(@visit.survey) %>. Zum nächsten | vorherigen Besuch wechseln. Alle durch <%= @visit.survey.project.name %> besuchte Orte <%= link_to "ansehen", project_path(@visit.survey.project) %>.
  </p>
  <p>
    Siedlungsplatz von <%= link_to "#{@visit.survey.site.name}", site_path(@visit.survey.site) %> <%= link_to "(#{@visit.survey.number})", survey_path(@visit.survey) %> für das Projekt <%= link_to "#{@visit.survey.project.name}", project_path(@visit.survey.project) %>. Besuch am <strong><%= link_to "#{@visit.start_date.strftime("%d.%m.%Y")}", survey_visit_path(@visit.survey, @visit) %></strong>.<br />
    Dauer: <%= convert_seconds_to_time(@visit.start_date, @visit.end_date) %> (zwischen <%= @visit.start_date.strftime("%H:%M") %> und <%= @visit.end_date.strftime("%H:%M") %>).
  </p>
<% end %>

<% content_for :text do %>
<% for document in @visit.documents %>
  <p>
    <% if document.title.empty? %>
      <strong><%= document.documenttype %></strong>
    <% else %>
      <strong><%= document.title %></strong> (<%= document.documenttype %>)
    <% end %>
    <% if logged_in? %>
      <small><%= link_to "Bearbeiten", edit_document_path(document) if can? :edit, @site %></small>
    <% end %>
  </p>
  <p><%= document.content %></p>
<% end %>

<% end %>

<% content_for :media do %>
    <ul class="nav nav-tabs" id="rightTab">
      <li class="active"><a href="#images" data-toggle="tab">Ansichten</a></li>
      <li><a href="#maps" data-toggle="tab">Karten</a></li>
      <li><a href="#drawings" data-toggle="tab">Pläne und Skizzen</a></li>
    </ul>
    <div class="tab-content">
      <div class="tab-pane active" id="images">
        <%= render :partial => "shared/imagetab", :locals => { :visit => @visit, :tab => "Ansicht", :dtab => nil } %>
      </div>
      <div class="tab-pane" id="maps">
        <%= render :partial => "shared/imagetab", :locals => { :visit => @visit, :tab => "Karte", :dtab => nil } %>
      </div>
      <div class="tab-pane" id="drawings">
        <%= render :partial => "shared/imagetab", :locals => { :visit => @visit, :tab => "Plan", :dtab => "Skizze" } %>
      </div>
    </div>
<% end %>

<% content_for :links do %>
  <% if can? :edit, @visit %>
    <div class="row">
      <div class="span3">
        <ul class="unstyled">
          <li><%= link_to "Neuer Bericht", new_document_path(:documentable_type => @visit.class, :documentable_id => @visit) %></li>
          <li><%= link_to "Zuvor hochgeladene Bilder verknüpfen", new_imagetag_path(:imageable_id => @visit, :imageable_type => @visit.class) %></li>
          <a href="#add-image" role="button" data-toggle="modal">Bild direkt zu diesem Besuch hochladen</a>
        </ul>
      </div>
      <div class="span2 text-right">
        <%= link_to "Bearbeiten", edit_survey_visit_path(@visit.survey, @visit), :class => 'btn btn-small' %>
      <%= link_to "Löschen", [@visit.survey, @visit], :confirm => 'Are you sure?', :method => :delete, :class => 'btn btn-small btn-danger' %>
      </div>
    </div>


    <div id="add-image" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h3 id="myModalLabel">Upload eines Bildes zu <%= @visit.start_date.strftime("%d.%m.%Y") %></h3>
      </div>
      <%= form_for Image.new, :html => { :class => 'form-horizontal', :multipart => true } do |f| %>
        <%= f.hidden_field :imageable_id, :value => @visit.id %>
        <%= f.hidden_field :imageable_type, :value => @visit.class %>
        <div class="modal-body">
          <div class="control-group">
            <%= f.label :name, :class => 'control-label' %>
            <div class="controls">
              <%= f.text_field :name, :class => 'text_field' %>
            </div>
          </div>
          <div class="control-group">
            <%= f.label :description, :class => 'control-label' %>
            <div class="controls">
              <%= f.text_area :description, :class => 'text_area', :rows => 3 %>
            </div>
          </div>
          <div class="control-group">
            <%= f.label :imagefile, :class => 'control-label' %>
            <div class="controls">
              <%= f.file_field :imagefile, :class => 'text_field' %>
            </div>
          </div>
          <div class="control-group">
            <%= f.label :imagetype, :class => 'control-label' %>
            <div class="controls">
              <%= f.select(:imagetype, Image::IMAGETYPES, :class => 'text_field') %>
            </div>
          </div>
        </div>
        <div class="modal-footer">
          <%= f.submit "Speichern", :class => "btn btn-primary" %>
          <button class="btn" data-dismiss="modal" aria-hidden="true">Abbrechen</button>
        </div>
      <% end %>
    </div>

  <% end %>
<% end %>