config/routes.rb
Tavo::Application.routes.draw do  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "signup" => "users#new", :as => "signup"
  resources :users
  resources :sessions
  resources :password_resets
  get "dashboard" => "dashboard#index"
  
  resources :projects
  resources :references
  resources :documents
  resources :images
  resources :imagetags
  resources :sites
  resources :appellations
  resources :districts
  resources :people
  post "user_connect" => "people#connect_to_user"
  resources :surveys do
    resources :visits
  end

  root :to => 'discover#index'

end

app/models/project.rb
class Project < ActiveRecord::Base
  stampable

  attr_accessible :name, :description, :method, :creator_id, :updater_id, :responsible_id, :memberships_attributes
  has_many :surveys
  has_many :documents, :as => :documentable, :dependent => :destroy
  has_many :memberships

  accepts_nested_attributes_for :memberships, :allow_destroy => true

  validates_presence_of :name

  def projectdescription
  	documents.where("documenttype = ?", "Projektbeschreibung").first
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
    @projects = Project.all
    render :layout => "index_template"
  end

  def show
    @project = Project.find(params[:id])
    render :layout => "show_template"
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(params[:project])
    if @project.save
      redirect_to @project, :notice => "Successfully created project."
    else
      render :action => 'new'
    end
  end

  def edit
    @project = Project.find(params[:id])
  end

  def update
    @project = Project.find(params[:id])
    if @project.update_attributes(params[:project])
      redirect_to @project, :notice  => "Successfully updated project."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @project = Project.find(params[:id])
    @project.destroy
    redirect_to projects_url, :notice => "Successfully destroyed project."
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper

end

app/views/projects/_form.html.erb
<%= nested_form_for @project, :html => { :class => 'form-horizontal'} do |f| %>
  <%= f.error_messages %>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>


  <%= f.fields_for :memberships do |builder| %>
    <%= render "membership_fields", :f => builder %>
  <% end %>
  <div class="control-group">
    <p style="padding-bottom:20px;"><%= f.link_to_add "Einen Mitarbeiter hinzufügen", :memberships %></p>
  </div>

  <div class="control-group">
    <%= f.label :description, "Projektbeschreibung", :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :description, :class => 'text_field span5' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :method, "Vorgehensweise", :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :method, :class => 'text_field span5' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit "Speichern", :class => 'btn btn-primary' %>
    <% if @project.new_record? %>
      <%= link_to 'Abbrechen', projects_path, :class => 'btn' %>
    <% else %>
      <%= link_to 'Abbrechen', @project, :class => 'btn' %>
    <% end %>
  </div>
<% end %>

app/views/projects/_membership_fields.html.erb
<div class="field", style="border:1px dashed #eee; padding:20px 0 10px 0; margin-top:5px;">
  <div class="control-group">
    <%= f.label :person_id, 'Account (optional)', :class => 'control-label' %>
    <div class="controls controls-row">
      <%= f.collection_select(:person_id, Person.all, :id, :fullname) %>
      <small><%= f.link_to_remove "entfernen" %></small>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :task, 'Aufgabe', :class => 'control-label' %>
    <div class="controls">
      <%= f.select(:task, Membership::TASKS, :class => 'select-field') %>
    </div>
  </div>
  
</div>

app/views/projects/edit.html.erb
<% title "Projekt bearbeiten" %>

<%= render 'form' %>

app/views/projects/index.html.erb
<% title "Projekte" %>

<% content_for :overview do %>
  <p>
    
  </p>
<% end %>

<% content_for :thead do %>
  <tr>
    <th class="span7">Bezeichnung</th>
    <% if logged_in? %>
      <th></th>
    <% end %>
  </tr>
<% end %>
<% content_for :tbody do %>
  <% for project in @projects %>
    <tr>
      <td>
        <%= link_to "#{project.name}", project %><br />
        <% unless project.description == nil %>
          <small><%= truncate(project.description, :length => 200, :separator => ' ') %></small>
        <% end %>
      </td>
      <% if logged_in? %>
        <td style="text-align:right;">
          
        </td>
      <% end %>
    </tr>
  <% end %>
<% end %>

<% content_for :indexsidebar do %>
  <p></p>
<% end %>

app/views/projects/new.html.erb
<% title "Neues Projekt" %>

<%= render 'form' %>

app/views/projects/show.html.erb
<% title "Projekt #{@project.name}" %>
<% content_for :overview do %>
  <%= @project.responsible_id %>
  <%= @project.creator_id %>
  <%= @project.updater_id %>
  <p>Hier erscheinen Dinge wie: wann angelegt, durch wen, letzte änderung durch wen, wer verantwortlich</p>
<% end %>

<% content_for :text do %>
  <div id="surveys">
    <table class="table table-striped">
      <thead>
        <tr>
          <th class="span1">Projekt</th>
          <th class="span1">Nummer</th>
          <th class="span5">Siedlungsplatz</th>
          <% if logged_in? %>
            <th></th>
          <% end %>
        </tr>
      </thead>
      <tbody>
        <% for survey in @project.surveys %>
        <tr>
          <td><%= survey.project.name %></td>
          <td><%= link_to "#{survey.number}", survey_path(survey) %></td>
          <td>
            <ul class="unstyled">
              <li>
                <%= link_to "#{survey.site.name}", survey_path(survey) %> 
              </li>
              <li><small><%= count_visits(survey) %></small></li>
            </ul>
          </td>
          <% if logged_in? %>
            <td style="text-align:right;">
              
            </td>
          <% end %>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>


  <div id="descriptions">
  	<h4>Projektbeschreibung</h4>
    <p><%= @project.description %></p>
    <h4>Vorgehensweise</h4>
    <p><%= @project.method %></p>

    <h4>Tagebuch</h4>
    <p><%= @project.documents.inspect %></p>
    <small><%= link_to "Neuer Tagebucheintrag", new_document_path(:documentable_type => @project.class, :documentable_id => @project) if can? :edit, @project %></small>
  </div>
<% end %>

<% content_for :links do %>
  <% if can? :edit, @project %>
    <div class="row">
      <div class="span3">
	  
	    </div>
	    <div class="span2 text-right">
	      <%= link_to "Bearbeiten", edit_project_path(@project), :class => 'btn btn-small' %>
        <%= link_to "Löschen", @project, :confirm => 'Are you sure?', :method => :delete, :class => 'btn btn-small btn-danger' %>
      </div>
    </div>
  <% end %>
<% end %>

<% content_for :media do %>
  <p style="padding-bottom:250px;">Hierher kommt was vor kurzem alles in diesem Projekt passierte</p>


  <h4>Mitarbeiter dieses Projektes</h4>
  <table class="table table-striped">
    <tbody>
      <% for membership in @project.memberships %>
        <tr>
          <td><%= link_to "#{membership.person.fullname}", person_path(membership.person) %></td>
          <td><%= membership.task %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>