config/routes.rb
Tavo::Application.routes.draw do  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "signup" => "users#new", :as => "signup"
  resources :users
  resources :sessions
  resources :password_resets
  get "dashboard" => "dashboard#index"
  
  resources :projects
  resources :references
  resources :documents
  resources :images
  resources :imagetags
  resources :sites
  resources :appellations
  resources :districts
  resources :people
  post "user_connect" => "people#connect_to_user"
  resources :surveys do
    resources :visits
  end

  root :to => 'discover#index'

end

app/models/survey.rb
class Survey < ActiveRecord::Base
  stampable
  attr_accessible :project_id, :number, :site_id, :creator_id, :updater_id, :citations_attributes
  belongs_to :project
  belongs_to :site
  has_many :visits
  has_many :citations, :as => :citable, :dependent => :destroy
  has_many :references, :through => :citations

  accepts_nested_attributes_for :citations, :reject_if => lambda { |a| a[:reference_id].blank? }, :allow_destroy => true
  
  validates_presence_of :project_id, :number, :site_id
end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController
  def index
    #@site = Site.find(params[:site_id])
    @surveys = Survey.all
    #render :layout => "index_template"
  end

  def show
    @survey = Survey.find(params[:id])
    render :layout => "show_template"
  end

  def new
    @site = Site.find(params[:site_id])
    @survey = Survey.new(:site_id => @site.id)
  end

  def create
    @survey = Survey.new(params[:survey])
    if @survey.save
      redirect_to @survey, :notice => "Successfully created survey."
    else
      render :action => 'new'
    end
  end

  def edit
    #@site = Site.find(params[:site_id])
    #@survey = @site.surveys.find(params[:id])
    @survey = Survey.find(params[:id])
  end

  def update
    @survey = Survey.find(params[:id])
    if @survey.update_attributes(params[:survey])
      redirect_to @survey, :notice  => "Successfully updated survey."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @survey = Survey.find(params[:id])
    @survey.destroy
    redirect_to surveys_url, :notice => "Successfully destroyed survey."
  end
end

app/helpers/surveys_helper.rb
module SurveysHelper
end

app/views/surveys/_form.html.erb
<%= nested_form_for @survey, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.error_messages %>
  <%= f.hidden_field :site_id %>
  <div class="control-group">
    <%= f.label :project_id, 'Projekt', :class => 'control-label' %>
    <div class="controls">
      <%= f.collection_select(:project_id, Project.all, :id, :name) %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :number, 'Ortsnummer', :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :number, :class => 'text_field' %>
    </div>
  </div>

  <%= f.fields_for :citations do |builder| %>
    <%= render "shared/citation_fields", :f => builder %>
  <% end %>
  <div class="controls">
    <p><%= f.link_to_add "Zitat hinzufügen", :citations %></p>
  </div>

  <div class="form-actions">
    <%= f.submit "Speichern", :class => 'btn btn-primary' %>
    <% if @survey.new_record? %>
      <%= link_to 'Abbrechen', @survey.site, :class => 'btn' %>
    <% else %>
      <%= link_to 'Abbrechen', @survey, :class => 'btn' %>
    <% end %>
  </div>
<% end %>

app/views/surveys/edit.html.erb
<% title "Edit Survey" %>
<p>
  <strong>Name:</strong>
  <%= @survey.site.name %>
</p>
<p>
  <strong>Bezirk:</strong>
  <%= @survey.site.district.name %>
</p>
<%= render 'form' %>

app/views/surveys/index.html.erb
<% title "nicht vorgesehen" %>

<% content_for :overview do %>
  <p>
    
  </p>
<% end %>

<% content_for :thead do %>
  <tr>
    <th class="span1">Projekt</th>
    <th class="span1">Nummer</th>
    <th class="span5">Siedlungsplatz</th>
    <% if logged_in? %>
      <th></th>
    <% end %>
  </tr>
<% end %>
<% content_for :tbody do %>
  <% for survey in @surveys %>
    <tr>
      <td><%= survey.project.name %></td>
      <td><%= link_to "#{survey.number}", survey_path(survey) %></td>
      <td>
        <ul class="unstyled">
          <li>
            <%= link_to "#{survey.site.name}", survey_path(survey) %> 
          </li>
          <li><small><%= count_visits(survey) %></small></li>
        </ul>
      </td>
      <% if logged_in? %>
        <td style="text-align:right;"><%= link_to "Bearbeiten", edit_survey_path(survey), :class => 'btn btn-mini' %></td>
      <% end %>
    </tr>
  <% end %>
<% end %>

<% content_for :indexsidebar do %>
  <p>some text</p>
<% end %>

app/views/surveys/new.html.erb
<% title "Neue Begehung" %>
<p>
  <strong>Name:</strong>
  <%= @site.name %>
</p>
<p>
  <strong>District:</strong>
  <%= @site.district.name %>
</p>
<%= render 'form' %>

app/views/surveys/show.html.erb
<% title "Begehung von #{@survey.site.name}" %>

<% content_for :overview do %>
<p>
  <strong>Project:</strong>
  <%= @survey.project.name %><br /> 
  <strong>Bezirk:</strong> 
  <%= @survey.site.district.name %> 
</p>
<p>
  <strong>Siedlungsplatz:</strong>
  <%= @survey.site.name %> <small>(<%= link_to "zur Siedlungsplatzansicht", @survey.site %>)</small><br />
  <strong>Kurzbezeichnung:</strong>
  <%= @survey.number %>
</p>
<p>
  <%= link_to "Alle Siedlungsplätze ansehen", sites_path %>
</p>
<% end %>

<% content_for :text do %>
  <% unless @survey.visits.empty? %>
    <table class="table table-striped">
      <thead>
        <tr>
          <th class="span2">Datum</th>
          <th class="span3">Dauer</th>
          <% if logged_in? %>
            <th></th>
          <% end %>
        </tr>
      </thead>
      <tbody>
        <% for visit in @survey.visits %>
          <tr>
            <td><%= link_to "#{visit.start_date.strftime("%d.%m.%Y")}", survey_visit_path(visit.survey, visit) %></td>
            <td><%= convert_seconds_to_time(visit.start_date, visit.end_date) %></td>
            <% if logged_in? %>
              <td style="text-align:right;">
                
              </td>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>
    <% for visit in @survey.visits %>
      <h4>Verknüpfungen zum Besuch am <%= visit.start_date.strftime("%d.%m.%Y") %></h4>
      <%= render :partial => "shared/imagetab", :locals => { :visit => visit, :tab => "Ansicht", :dtab => nil } %>
    <% end %>
  <% end %>
<% end %>

<% content_for :links do %>
<% if can? :edit, @survey %>
  <div class="row">
    <div class="span3">
      <%= link_to "Neuen Besuch aufnehmen", new_survey_visit_path(@survey) %><br />
      <%= link_to "Literaturverweis erstellen" %>
    </div>
    <div class="span2 text-right">
      <%= link_to "Bearbeiten", edit_survey_path(@survey), :class => 'btn btn-small' %>
      <%= link_to "Löschen", @survey, :confirm => 'Are you sure?', :method => :delete, :class => 'btn btn-small btn-danger' %>
    </div>
  </div>
<% end %>
<% end %>

<% content_for :media do %>
<h4>Literatur zu dieser Begehung</h4>
      <ul>
        <% for cite in @survey.citations %>
          <li><%= raw cite_entry(cite) %></li>
        <% end %>
      </ul>
<% end %>