config/routes.rb
Tavo::Application.routes.draw do  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "signup" => "users#new", :as => "signup"
  resources :users
  resources :sessions
  resources :password_resets
  get "dashboard" => "dashboard#index"
  
  resources :projects
  resources :references
  resources :documents
  resources :images
  resources :imagetags
  resources :sites
  resources :appellations
  resources :districts
  resources :people
  post "user_connect" => "people#connect_to_user"
  resources :surveys do
    resources :visits
  end

  root :to => 'discover#index'

end

app/models/reference.rb
class Reference < ActiveRecord::Base
  attr_accessible :title, :year, :creator_id, :updater_id, :publishing_place, :person_ids, :parent_id, :first_page, 
  				  :last_page, :referencetype, :alternative_author, :volume_number

  stampable
  has_ancestry

  has_many :citations
  has_and_belongs_to_many :people

  validates_presence_of :referencetype, :title

  REFERENCETYPES = %w[Monographie Reihe Sammelwerk Zeitschrift] # ohne Artikel. Dieser wird als hidden_field-value übergeben.

  def self.possible_parents(root, subtree)
    possible_parents = subtree_of(roots.where('name = ?', root))
    if subtree.present?
      possible_parents = possible_parents.where("id not in (?)", subtree)
    end
    possible_parents
  end


  def entry
    people.map(&:fullname).join(", ") + ", " + year.strftime("%Y") + ", " + title
  end
end

app/controllers/references_controller.rb
class ReferencesController < ApplicationController
  def index
    @references = Reference.roots
    render :layout => "index_template"
  end

  def show
    @reference = Reference.find(params[:id])
    @articles = @reference.children
    render :layout => "show_template"
  end

  def new
    @reference = Reference.new(:parent_id => params[:parent_id])
  end

  def create
    @reference = Reference.new(params[:reference])
    if @reference.save
      redirect_to @reference, :notice => "Successfully created reference."
    else
      render :action => 'new'
    end
  end

  def edit
    @reference = Reference.find(params[:id])
  end

  def update
    @reference = Reference.find(params[:id])
    if @reference.update_attributes(params[:reference])
      redirect_to @reference, :notice  => "Successfully updated reference."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @reference = Reference.find(params[:id])
    @reference.destroy
    redirect_to references_url, :notice => "Successfully destroyed reference."
  end
end

app/helpers/references_helper.rb
module ReferencesHelper

end

app/views/references/_form.html.erb
<%= form_for @reference, :html => { :class => 'form-horizontal'} do |f| %>
  <%= f.error_messages %>
  <% if @reference.parent_id %>
  <div style="margin-bottom:40px;">
    Einen Artikel in <strong><%= @reference.parent.people.map(&:fullname).join(", ") %> (Hrsg.), <%= @reference.parent.year.strftime("%Y") %>, <em><%= link_to "#{@reference.parent.title}", @reference.parent %></em>, <%= @reference.parent.publishing_place %></strong> anlegen.
  </div>
  <% end %>

  <% unless @reference.parent_id %>
    <div class="control-group">
      <%= f.label :referencetype, "Typ", :class => 'control-label' %>
      <div class="controls">
        <%= f.select(:referencetype, Reference::REFERENCETYPES, :class => 'select-field span3') %>
      </div>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :person_ids, "Autoren", :class => 'control-label' %>
    <div class="controls">
      <%= collection_select(:reference, :person_ids, Person.find(:all), :id, :fullname, { }, {:multiple => true, :class => 'text_field'}) %>
    </div>
  </div>

  <% unless @reference.parent_id %>
  <!--
    <div class="control-group">
      <%= f.label :alternative_author, "Anderer Herausgeber", :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :alternative_author, :class => 'text_field' %>
      </div>
    </div>
  -->
  <% end %>

  <div class="control-group">
    <%= f.label :title, "Titel", :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :title, :class => 'text_field' %>
    </div>
  </div>


  <% if @reference.parent_id %>
    <%= f.hidden_field :referencetype, :value => "Artikel" %>
    <div id="article">
      <div class="control-group">
        <%= f.label :first_page, "Erste Seite", :class => 'control-label' %>
        <div class="controls">
          <%= f.text_field :first_page, :class => 'text_field' %>
        </div>
      </div>
      <div class="control-group">
        <%= f.label :last_page, "Letzte Seite", :class => 'control-label' %>
        <div class="controls">
          <%= f.text_field :last_page, :class => 'text_field' %>
        </div>
      </div>
    </div>
  <% end %>

  <% unless @reference.parent_id %>
    <div id="notarticle">
      <div class="control-group">
        <%= f.label :year, "Erscheinungsjahr", :class => 'control-label' %>
        <div class="controls">
          <%= f.date_select :year, {:start_year => Time.now.year + 1, :end_year => Time.now.year - 130, :discard_day => true, :discard_month => true, :include_blank => true}, :class => 'text_field' %>
        </div>
      </div>
      <div class="control-group">
        <%= f.label :publishing_place, "Erscheinungsort", :class => 'control-label' %>
        <div class="controls">
          <%= f.text_field :publishing_place, :class => 'text_field' %>
        </div>
      </div>
    </div>
  
    <div id="Zeitschrift">
      <div class="control-group">
        <%= f.label :volume_number, "Band Nr.", :class => 'control-label' %>
        <div class="controls">
          <%= f.text_field :volume_number, :class => 'text_field' %>
        </div>
      </div>
    </div>
<% end %>

  <div class="form-actions">
    <%= f.submit "Speichern", :class => 'btn btn-primary' %>
    <% if @reference.new_record? %>
      <% if @reference.parent_id %>
        <%= link_to 'Abbrechen', @reference.parent, :class => 'btn' %>
      <% else %>
        <%= link_to 'Abbrechen', references_path, :class => 'btn' %>
      <% end %>
    <% else %>
      <%= link_to 'Abbrechen', @reference, :class => 'btn' %>
    <% end %>
  </div>
<% end %>

app/views/references/edit.html.erb
<% title "Literatur bearbeiten" %>

<%= render 'form' %>

app/views/references/index.html.erb
<% title "Literatur" %>

<% content_for :overview do %>
  <p>
    
  </p>
<% end %>

<% content_for :thead do %>


  <tr>
    <th></th>
    <% if can? :edit, @references %>
      <th></th>
    <% end %>
  </tr>
<% end %>
<% content_for :tbody do %>
  <% for reference in @references %>
    <tr>
      <td>
        <%= reference.people.map(&:fullname).join(", ") %>
        <%= reference.year.strftime("%Y") %>, 
        <%= link_to "#{reference.title}", reference %>, 
        <%= reference.publishing_place %>.

        <br />
        <% unless reference.referencetype == "Monographie" || reference.referencetype == "Artikel" %>
        <ul style="padding-left:20px;" class="unstyled">
          <% for article in reference.children.order("first_page ASC") do %>
            <li><%= article.people.map(&:fullname).join(", ") %>, <%= link_to "#{article.title}", article %>, <%= article.first_page %>-<%= article.last_page %>.</li>
          <% end %>
        </ul>
        <% end %>

      </td>
      <% if can? :edit, reference %>
        <td style="text-align:right;">
          <%= link_to "Bearbeiten", edit_reference_path(reference), :class => 'btn btn-small pull-right' %>
          <% unless reference.referencetype == "Monographie" || reference.referencetype == "Artikel" %>
            <%= link_to "Artikel anlegen", new_reference_path(:parent_id => reference), :class => 'btn btn-small' %>
          <% end %>
        </td>
      <% end %>
    </tr>
  <% end %>
<% end %>

<% content_for :indexsidebar do %>
  <p></p>
<% end %>

app/views/references/new.html.erb
<% title "Literatur hinzufügen" %>

<%= render 'form' %>

app/views/references/show.html.erb
<% title "Literatureintrag" %>
<% content_for :overview do %>
  <p>
    <strong>
      <% if @reference.referencetype == "Monographie" || @reference.referencetype == "Artikel" %>
        Autor:
      <% else %>
        Herausgeber:
      <% end %>
    </strong> 
    <%= @reference.people.map(&:fullname).join(", ") %>
  </p>
  <p>
    <strong>Title:</strong>
    <%= @reference.title %> <%= "("+@reference.referencetype+")" if @reference.is_root? %>
  </p>

  <% if @reference.referencetype == "Artikel" %>
    <p><strong>Erschienen in: </strong><%= @reference.parent.people.map(&:fullname).join(", ") %> (Hrsg.), <%= @reference.parent.year.strftime("%Y") %>, <%= link_to "#{@reference.parent.title}", @reference.parent %>, <%= @reference.first_page %>-<%= @reference.last_page %>, <%= @reference.parent.publishing_place %>.</p>
  <% else %>
    <p>
      <strong>Erscheinungsjahr:</strong>
      <%= @reference.year.strftime("%Y") %>
    </p>
    <p>
      <strong>Erscheinungsort:</strong>
      <%= @reference.publishing_place %>
    </p>
  <% end %>

  <%= link_to "Zurück zu Übersicht", references_path %>
<% end %>

<% content_for :text do %>
<% unless @reference.referencetype == "Monographie" || @reference.referencetype == "Artikel" %>
<h4>Inhalt</h4>
  <ul class="unstyled">
    <% for article in @articles.order("first_page ASC") do %>
      <li><%= article.people.map(&:fullname).join(", ") %>, <%= link_to "#{article.title}", article %>, <%= article.first_page %>-<%= article.last_page %></li>
    <% end %>
  </ul>
<% end %>
<% end %>

<% content_for :links do %>
  <% if can? :edit, @reference %>
    <%= link_to "Bearbeiten", edit_reference_path(@reference), :class => 'btn btn-small pull-right' %>
    <%= link_to "Löschen", @reference, :confirm => 'Are you sure?', :method => :delete, :class => 'btn btn-small btn-danger pull-right' %>
    <% unless @reference.referencetype == "Monographie" || @reference.referencetype == "Artikel" %>
      <%= link_to "Artikel in diesem Buch anlegen", new_reference_path(:parent_id => @reference) %>
    <% end %>
  <% end %>
<% end %>